version: '3.8'

services:
  app:
    build:
      context: . # Lấy toàn bộ thư mục hiện tại làm ngữ cảnh để xây dựng.
      dockerfile: Dockerfile # Sử dụng tệp Dockerfile của bạn.
      target: production # ra lệnh cho Docker chỉ xây dựng đến giai đoạn production trong Dockerfile đa giai đoạn của bạn
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=lms_user
      - DATABASE_PASSWORD=lms_password
      - DATABASE_NAME=lms_ai_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKUP_DIR=/app/backups
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads # thư mục uploads trên máy thật của bạn sẽ được ánh xạ vào thư mục /app/uploads bên trong container.
      - ./backups:/app/backups
      - ./logs:/app/logs
    networks: # kết nối "trụ sở" vào "hệ thống đường nội bộ lms-network".
      - lms-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lms_ai_database
      - MYSQL_USER=lms_user
      - MYSQL_PASSWORD=lms_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./backups:/backups
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      timeout: 3s
      retries: 5

  # Database monitoring tool (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=lms_user
      - PMA_PASSWORD=lms_password
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - lms-network
    profiles:
      - tools

  # Redis monitoring tool (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - lms-network
    profiles:
      - tools

  # AI Python Service (sẽ được thêm trong các phần sau)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ai-service:/app
      - ai_models:/app/models
    networks:
      - lms-network
    restart: unless-stopped
    profiles: # khi bạn chạy docker-compose up, dịch vụ này sẽ KHÔNG khởi động.
      - ai

volumes:
  mysql_data:
  redis_data:
  ai_models:

networks:
  lms-network:
    driver: bridge


# Để khởi động mọi thứ (trừ AI): docker-compose up
# Để khởi động mọi thứ (bao gồm cả AI): docker-compose --profile ai up
# Để tắt mọi thứ: docker-compose down