export const FORUM_CONSTANTS = {
  REPUTATION: {
    DEFAULT_SCORE: 0,
    UPVOTE_POINTS: 1,
    DOWNVOTE_POINTS: -1,
    ACCEPTED_ANSWER_POINTS: 15,
    QUESTION_UPVOTE_POINTS: 5,
    ANSWER_UPVOTE_POINTS: 10,
    HELPFUL_VOTE_POINTS: 2,
    EXPERT_BONUS_MULTIPLIER: 1.5,
    DAILY_LIMIT: 200,
    WEEKLY_LIMIT: 1000,
  },
  LIMITS: {
    MIN_TITLE_LENGTH: 5,
    MAX_TITLE_LENGTH: 200,
    MIN_CONTENT_LENGTH: 10,
    MAX_CONTENT_LENGTH: 50000,
    MAX_TAGS_PER_POST: 5,
    MAX_ATTACHMENTS_PER_POST: 10,
    MAX_REPORTS_PER_USER_PER_DAY: 20,
    MAX_VOTES_PER_USER_PER_DAY: 100,
  },
  SEARCH: {
    MIN_SEARCH_LENGTH: 3,
    MAX_SEARCH_LENGTH: 100,
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
  },
  MODERATION: {
    AUTO_LOCK_AFTER_DAYS: 365,
    AUTO_ARCHIVE_AFTER_DAYS: 730,
    SPAM_THRESHOLD: 3,
    REPUTATION_THRESHOLD_FOR_VOTING: 15,
    REPUTATION_THRESHOLD_FOR_COMMENTING: 50,
    REPUTATION_THRESHOLD_FOR_MODERATION: 500,
  },
  BADGES: {
    FIRST_POST: { name: 'First Post', points: 10 },
    GOOD_QUESTION: { name: 'Good Question', points: 25 },
    GOOD_ANSWER: { name: 'Good Answer', points: 25 },
    GREAT_QUESTION: { name: 'Great Question', points: 100 },
    GREAT_ANSWER: { name: 'Great Answer', points: 100 },
    POPULAR_QUESTION: { name: 'Popular Question', points: 50 },
    NOTABLE_QUESTION: { name: 'Notable Question', points: 100 },
    FAMOUS_QUESTION: { name: 'Famous Question', points: 200 },
    EXPERT_CONTRIBUTOR: { name: 'Expert Contributor', points: 500 },
    COMMUNITY_MODERATOR: { name: 'Community Moderator', points: 1000 },
  },
};
