# Default values for lms-ai-backend
replicaCount: 3

image:
  repository: ghcr.io/your-org/lms-ai-backend
  pullPolicy: IfNotPresent
  tag: ''

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/rate-limit: '100'
  hosts:
    - host: api.lms-ai.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: lms-ai-tls
      hosts:
        - api.lms-ai.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Database configuration
database:
  host: 'lms-ai-mysql.database.svc.cluster.local'
  port: 3306
  name: 'lms_ai_production'

# Redis configuration
redis:
  host: 'lms-ai-redis.cache.svc.cluster.local'
  port: 6379
