export enum ActivityType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  COURSE_VIEW = 'course_view',
  LESSON_START = 'lesson_start',
  LESSON_COMPLETE = 'lesson_complete',
  LESSON_PROGRESS = 'lesson_progress',
  VIDEO_PLAY = 'video_play',
  VIDEO_START = 'video_start',
  VIDEO_RESUME = 'video_resume', 
  VIDEO_PAUSE = 'video_pause',
  VIDEO_SEEK = 'video_seek',
  VIDEO_COMPLETE = 'video_complete',
  VIDEO_SPEED_CHANGE = 'video_speed_change',
  VIDEO_QUALITY_CHANGE = 'video_quality_change',
  QUIZ_START = 'quiz_start',
  QUIZ_SUBMIT = 'quiz_submit',
  QUIZ_COMPLETE = 'quiz_complete',
  ASSIGNMENT_START = 'assignment_start',
  ASSIGNMENT_SUBMIT = 'assignment_submit',
  DISCUSSION_POST = 'discussion_post',
  CHAT_MESSAGE = 'chat_message',
  FILE_DOWNLOAD = 'file_download',
  SEARCH = 'search',
  BOOKMARK_ADD = 'bookmark_add',
  NOTE_CREATE = 'note_create',
  HELP_REQUEST = 'help_request',
  COURSE_COMPLETE = 'course_complete',
  CERTIFICATE_EARN = 'certificate_earn',
  ASSESSMENT_START = 'assessment_start',
  FORUM_POST = 'forum_post',
  CONTENT_READ = 'content_read',
  CONTENT_SCROLL = 'content_scroll',
  CONTENT_FOCUS = 'content_focus', 
  CONTENT_BLUR = 'content_blur',
  TAB_SWITCH = 'tab_switch',
  WINDOW_BLUR = 'window_blur',
  WINDOW_FOCUS = 'window_focus',
  NOTE_UPDATED = 'note_updated',
  BOOKMARK_CREATED = 'bookmark_created',
  RESOURCE_DOWNLOAD = 'resource_download',
  INTERACTIVE_COMPLETED = 'interactive_completed',
  QUIZ_ATTEMPT = 'quiz_attempt',
}

export enum DeviceType {
  DESKTOP = 'desktop',
  TABLET = 'tablet',
  MOBILE = 'mobile',
  UNKNOWN = 'unknown',
}

export enum SessionStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  ABANDONED = 'abandoned',
  TIMED_OUT = 'timed_out',
}

export enum PerformanceLevel {
  EXCELLENT = 'excellent',
  GOOD = 'good',
  AVERAGE = 'average',
  BELOW_AVERAGE = 'below_average',
  POOR = 'poor',
}

export enum LearningPatternType {
  CONSISTENT = 'consistent',
  BINGE_LEARNER = 'binge_learner',
  PROCRASTINATOR = 'procrastinator',
  PERFECTIONIST = 'perfectionist',
  EXPLORER = 'explorer',
  FOCUSED = 'focused',
  SOCIAL_LEARNER = 'social_learner',
  INDEPENDENT = 'independent',
  CRAMMING = 'cramming',
  PROCRASTINATION = 'procrastination',
  DETAIL_ORIENTED = 'detail_oriented',
  STRUGGLING = 'struggling',
  SOCIAL = 'social',
}
