export enum SettingCategory {
  GENERAL = 'general',
  SECURITY = 'security',
  EMAIL = 'email',
  NOTIFICATIONS = 'notifications',
  INTEGRATIONS = 'integrations',
  APPEARANCE = 'appearance',
  LEARNING = 'learning',
  ASSESSMENT = 'assessment',
  COMMUNICATION = 'communication',
  ANALYTICS = 'analytics',
  AI = 'ai',
  STORAGE = 'storage',
  PERFORMANCE = 'performance',
  COMPLIANCE = 'compliance',
}

export enum SettingType {
  STRING = 'string',
  TEXT = 'text',
  NUMBER = 'number',
  INTEGER = 'integer',
  BOOLEAN = 'boolean',
  EMAIL = 'email',
  URL = 'url',
  JSON = 'json',
  ARRAY = 'array',
  DATE = 'date',
  TIME = 'time',
  COLOR = 'color',
  FILE = 'file',
}

export enum AuditAction {
  LOGIN = 'login',
  LOGIN_2FA_REQUIRED = 'login_2fa_required',
  USER_LOGIN_2FA_SUCCESS = 'user_login_2fa_success',
  LOGIN_2FA_COMPLETED = 'login_2fa_completed',
  USER_REGISTERED = 'user_registered',
  USER_UPDATED = 'user_updated',
  USER_DELETED = 'user_deleted',
  LOGOUT = 'logout',
  USER_LOGOUT = 'user_logout',
  USER_LOGOUT_ALL_DEVICES = 'user_logout_all_devices',
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  IMPORT = 'import',
  EXPORT = 'export',
  UPLOAD = 'upload',
  DOWNLOAD = 'download',
  APPROVE = 'approve',
  REJECT = 'reject',
  SUSPEND = 'suspend',
  ACTIVATE = 'activate',
  RESET_PASSWORD = 'reset_password',
  CHANGE_PASSWORD = 'change_password',
  GRANT_PERMISSION = 'grant_permission',
  PASSWORD_RESET_REQUESTED = 'password_reset_requested',
  PASSWORD_RESET_COMPLETED = 'password_reset_completed',
  REVOKE_PERMISSION = 'revoke_permission',
  SYSTEM_CONFIG = 'system_config',
  BACKUP = 'backup',
  RESTORE = 'restore',
  EMAIL_VERIFIED = 'email_verified',
  EMAIL_VERIFICATION_RESENT = 'email_verification_resent',
  SESSION_TERMINATED = 'session_terminated',
  CREATE_ASSESSMENT = 'create_assessment',
  UPDATE_ASSESSMENT = 'update_assessment',
  DELETE_ASSESSMENT = 'delete_assessment',
  CONFIGURE_ASSESSMENT = 'configure_assessment',
  PUBLISH_ASSESSMENT = 'publish_assessment',
  ARCHIVE_ASSESSMENT = 'archive_assessment',
  DUPLICATE_ASSESSMENT = 'duplicate_assessment',
  REMOVE_QUESTION = 'remove_question',
}

export enum AuditLevel {
  DEBUG = 'debug',
  INFO = 'info',
  WARNING = 'warning',
  ERROR = 'error',
  CRITICAL = 'critical',
}

export enum AuditStatus {
  SUCCESS = 'success',
  FAILED = 'failed',
  ERROR = 'error',
  PENDING = 'pending',
}
